version: '3.4'

services:
  monitoringdemo:
    image: ${DOCKER_REGISTRY-}monitoringdemo
    build:
      context: .
      dockerfile: MonitoringDemo/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s